name: Deploy to VPS

on:
  push:
    branches:
      - main  # Ganti jadi master kalau branch kamu namanya master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/craniora
            git pull origin main
            npm install
            npm run build
            pm2 restart craniora --update-env